# Generated by Django 3.2 on 2022-01-31 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Departments')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'Entity', 'verbose_name_plural': 'Entities'},
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.AddField(
            model_name='department',
            name='client',
            field=models.ManyToManyField(related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Clients'),
        ),
        migrations.AddField(
            model_name='department',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='accounts.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='department',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='accounts.entity', verbose_name='Entity'),
        ),
    ]
