# Generated by Django 3.2 on 2022-01-31 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220131_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='accounts.department', verbose_name='Department'),
        ),
    ]
